version: 1.0
provider:
  name: openfaas
  gateway: https://system.sjfisher.com
functions:
  go1:
    lang: golang-http
    handler: ./go1
    image: go1:latest
    image: functions/api-key-protected:latest
    secrets:
      - secret-api-key
    labels:
      com.openfaas.scale.min: "0"
      com.openfaas.scale.max: "10" 
